### ISSUE TITLE
new issues/ideas/features to work on?

### ISSUE THREAD

**Issue by surister** [Pringleman83/SportsBook#15]
Maybe redact a TODO.md with ideas/features or open some issues about that :P ?

**Comment by Pringleman83** [comment]
Great idea! I've added such a file now. Please take a read as I've put some important information in there regarding problems with merging when the file updated was the most up to date file at the time.

I've also put a link to a Slack work space so we can discuss future work, problems and ideas going forward. If you have another preferred communication platform, let us know.
