### ISSUE TITLE
Add pipfile perhaps an installation guide

### ISSUE THREAD

**Issue by surister** [Pringleman83/SportsBook#18]
Would be awesome to add a pipfile and a installation md.

That would ease new contributors and we can say pretty much that it's the canon for almost every open python project.

A pipfile is a file generated from 'pipenv' (a python packaging manager) it's the sum of pip and virtualvenv, using pipenv and having a pipfile, any new contributor would only need to write 1 command on their terminal to have anything they need (modules) automatically installed, all the process step by step would be written in the installation.md/howtouse.md/whatevername.md.

I could do that in no time once you approve of this.

**Comment by Pringleman83** [comment]
Yeah, feel free to do this. Thanks 👍🏻
