### ISSUE TITLE
Help, Predictions

### ISSUE THREAD

**Issue by SoccerCashUK** [Pringleman83/SportsBook#43]
Hi I`m guessing this is based on home win away win and draws
So this match is a draw Chojniczanka Chojnice 2 Bytovia Bytów 2 ?

But I have seen a match e.g. stockport 5  west ham 1
as stockport as 5 what does this mean please

James

**Comment by SoccerCashUK** [comment]
Hi thanks for your reply I understand now.
so is the matches based on per games e.g 10 H2H Home & Away
for expected goals

James

**Comment by SoccerCashUK** [comment]
By the way well done on this project

**Comment by Pringleman83** [comment]
@SoccerCashUK 

I'm not sure what you mean by 10 H2H Home & Away

Chojniczanka Chojnice 2 Bytovia Bytów 2 means it expects a 2-2 draw.

It's based on the team's goals scored on average per game and goals conceded on average per game. If it's the home team, it's looking at the goals that team have scored and conceded while playing at home only. If it's the away team, it's looking at the goals that team has scored and conceded away from home only.

There's also some maths included to consider tbot values.  It might not be the best way though.

**Comment by Pringleman83** [comment]
@SoccerCashUK 

The current system:

home_team_max_goals = home_team_avg_gpg_f * 2.5
away_team_max_goals = away_team_avg_gpg_f * 2.5
        
home_team_goals = int((home_team_avg_gpg_f * 1.25) * (away_team_avg_gpg_a))
 #gpg = Goals per game - f = For a = against
away_team_goals = int((away_team_avg_gpg_f * 1.25) * (home_team_avg_gpg_a))
        
if home_team_goals > home_team_max_goals:
    home_team_goals = home_team_max_goals
if away_team_goals > away_team_max_goals:
   away_team_goals = away_team_max_goals

**Comment by Pringleman83** [comment]
@SoccerCashUK 
That's interesting. I'm thinking of implementing a system where, if the current system predicts a team to win by 2 or more goals, it flags as a more likely win. Maybe a system that scanns all games for all leagues and brigns out these highlights.

**Comment by SoccerCashUK** [comment]
Yes thats what I was about to write to you either team that as 2 goals or more is the winning selection
yeah system be good ideal for this

**Comment by SoccerCashUK** [comment]
right doing this one
2pm kick off
Northampton Town 0 Forest Green Rovers 2
Away Win
Odds 2.80
£5 Win

**Comment by SoccerCashUK** [comment]
Barnsley was a winner home win odds 2.20

**Comment by Pringleman83** [comment]
Great stuff, good luck! I've got a crafty 5 fold on and Super6 done too lol

**Comment by SoccerCashUK** [comment]
good luck

**Comment by SoccerCashUK** [comment]
Are you from Bristol ?

**Comment by Pringleman83** [comment]
Nah, that's my surname. I'm from Birmingham.

**Comment by SoccerCashUK** [comment]
Cool, 
I have change some of the leagues to what I want in the py file 
As some are not good for goals

**Comment by Pringleman83** [comment]
@SoccerCashUK look at the TODO document. There's a link to join us on Slack. There's a general chat and we can PM.

**Comment by Pringleman83** [comment]
An option for "favourites" could be a good addition in the future.

**Comment by SoccerCashUK** [comment]
Already in slack

**Comment by Pringleman83** [comment]
In the SportsBook Slack? Drop me a pm.

On 13 Oct 2018 14:35, "SoccerCashUK" <notifications@github.com> wrote:

Already in slack

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Pringleman83/SportsBook/issues/43#issuecomment-429542385>,
or mute the thread

**Comment by SoccerCashUK** [comment]
sent
